# Generated by Django 4.0.6 on 2023-06-18 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0019_alter_classroom_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['-published'], 'verbose_name_plural': 'Classroom'},
        ),
    ]
