# Generated by Django 4.0.6 on 2023-06-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0021_alter_teacher_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='image',
            field=models.ImageField(default='profile_pic/no_image.jpg', max_length=255, upload_to='profile_pic/'),
        ),
    ]
