# Generated by Django 4.0.6 on 2023-06-22 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_alter_comment_options_teacherlogs_studentlogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherlogs',
            name='profile',
        ),
        migrations.DeleteModel(
            name='StudentLogs',
        ),
        migrations.DeleteModel(
            name='TeacherLogs',
        ),
    ]
