# Generated by Django 4.0.6 on 2023-07-12 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_student_profile_pic'),
        ('teacher', '0022_alter_classroom_image'),
        ('quiz', '0012_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(1, 'Grade 6'), (2, 'Grade 7'), (3, 'Grade 8'), (4, 'Grade 9')], default=1)),
                ('name', models.CharField(max_length=200)),
                ('questions', models.TextField(max_length=1000)),
                ('num', models.IntegerField(default=1)),
                ('created', models.DateField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('deadline', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateField()),
                ('title', models.CharField(default='', max_length=100)),
                ('body', models.TextField(default='', max_length=1000)),
                ('points', models.FloatField(default=0.0)),
                ('comments', models.CharField(default='', max_length=200)),
                ('worked', models.BooleanField(default=False)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.assignment')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
