# Generated by Django 4.0.6 on 2023-07-12 04:50

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_assignment_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='questions',
            field=froala_editor.fields.FroalaField(),
        ),
        migrations.AlterField(
            model_name='solution',
            name='body',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
