# Generated by Django 4.0.6 on 2023-07-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_alter_assignment_questions_alter_solution_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='assign/'),
        ),
    ]
