# Generated by Django 4.0.6 on 2023-07-16 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_listofcourses_listofquiz_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='choice',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
