# Generated by Django 4.0.6 on 2023-06-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0005_alter_parents_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parents',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/'),
        ),
    ]
