- !!python/object/apply:numpy.core.multiarray._reconstruct
  args:
  - &id001 !!python/name:numpy.ndarray ''
  - !!python/tuple
    - 0
  - !!binary |
    Yg==
  state: !!python/tuple
  - 1
  - !!python/tuple
    - 128
  - &id002 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - false
  - !!binary |
    AAAAQOsSwb8AAACA0VKgPwAAAEBzva0/AAAAQN/Elr8AAABA3OylvwAAAODE2a2/AAAAINg2sL8A
    AABAxwXDvwAAAACrMcA/AAAAICjnu78AAACAtF7SPwAAAADNlY2/AAAAAKqpw78AAACAwfDCvwAA
    AABEAm4/AAAAQBZfyj8AAAAAbCbPvwAAAAAwkry/AAAAQK+/sb8AAAAAgPeKvwAAAOCZZq0/AAAA
    AOHxsb8AAADA/d6yPwAAAIA3YKg/AAAAAB5upr8AAAAA4VfbvwAAAEC58cG/AAAAQOwiur8AAACg
    l6OWPwAAAAAGlpm/AAAAACmBqL8AAAAA/PSoPwAAAID6JcW/AAAAQPOwpL8AAACA+ByUvwAAAAAa
    hbQ/AAAAALg9Zb8AAAAgAqC7vwAAAECDqcg/AAAAwIn7kr8AAACANPbFvwAAAAAb56o/AAAAwKOu
    oj8AAABAa3rMPwAAAMBjkso/AAAAwFXIqj8AAAAA+46qPwAAAAAgtrS/AAAAoKobuj8AAACAyNzA
    vwAAAODd9pa/AAAAoG3RwD8AAADgSse2PwAAAAAnu6M/AAAAAMSujj8AAADg9+q6vwAAAABZJa0/
    AAAAAAlapz8AAADA173BvwAAAIDvin8/AAAAoBy7oT8AAABgMHTCvwAAAEDqjqi/AAAAAOpzsb8A
    AAAAwmPNPwAAAMDzJL4/AAAAILdSur8AAACg3BHFvwAAAADHcbs/AAAAAJzmur8AAADAZTK1vwAA
    AIA48Ja/AAAAwF5rzb8AAAAABM3JvwAAAABYk9W/AAAAAEWWlj8AAABgQGTUPwAAACDmsLU/AAAA
    wFR3yr8AAADA44StPwAAACDyBJ6/AAAAAO49ez8AAADA85G9PwAAAED1dck/AAAAAHWuj78AAAAA
    IEt9PwAAAKCirsG/AAAAAECBaD8AAABARVzFPwAAAODmHbO/AAAAQMLwnL8AAADANVnNPwAAAGDF
    FaK/AAAAQE/ZsT8AAADA1umAPwAAAADE/Jc/AAAAAN+mn78AAACgq0qxPwAAAOBDgMG/AAAAALoF
    jj8AAACgUrW6PwAAAAAdOHq/AAAAAFCcZT8AAAAAWOKiPwAAAOCHQb+/AAAAAMN5lj8AAACAq8uY
    vwAAAECzDag/AAAAAOJ0oT8AAAAAsQalvwAAAKCIYcK/AAAAALIstL8AAAAAeAe8PwAAAGBOx8m/
    AAAAILLNyj8AAABAE07RPwAAAKCDkqw/AAAAgCMwwD8AAAAA307BPwAAAGB87Lk/AAAAQNLeor8A
    AAAAvDKLPwAAAKDfoMm/AAAA4KjpiD8AAACAsaC0PwAAAADch6Y/AAAAgHy1oz8AAAAAl+mUPw==
- !!python/object/apply:numpy.core.multiarray._reconstruct
  args:
  - *id001
  - !!python/tuple
    - 0
  - !!binary |
    Yg==
  state: !!python/tuple
  - 1
  - !!python/tuple
    - 128
  - *id002
  - false
  - !!binary |
    AAAAwFYVub8AAAAAZiFyPwAAAKAf/Kc/AAAAQHj8lT8AAACAOTykvwAAAEAhyqO/AAAAwEqyp78A
    AACAWL3BvwAAAGBs1L8/AAAAgCqAu78AAACgRpzSPwAAAECBw5a/AAAAgMYavr8AAABgoabEvwAA
    AADgwYA/AAAAANGmxD8AAABAXQXOvwAAAICkELq/AAAAwDvHq78AAAAAvkaXvwAAAAC7hKc/AAAA
    gJJsn78AAACAHnC5PwAAAACg/5Y/AAAAAJuJtb8AAAAgmS7ZvwAAAACtlLi/AAAAgDMev78AAACA
    zZOyPwAAAAAenoG/AAAAgKTgqr8AAABAZ+mfPwAAAACu8Me/AAAAQJb6ob8AAAAA6maCPwAAAADa
    2bQ/AAAA4N4bqL8AAACgR4C2vwAAACBJj8k/AAAAQL+frr8AAAAATFzDvwAAAAAgSGs/AAAAAPx8
    oj8AAAAANqbMPwAAAMAoq8g/AAAA4Fb4sT8AAABAW3RxvwAAAICTorG/AAAAoJ6gwD8AAACAZ0LE
    vwAAAMADMnM/AAAAIKShvT8AAAAgmTiyPwAAAADIQqA/AAAAAEkcmD8AAABAT8m3vwAAAICjMLE/
    AAAAAHf8oz8AAACAPRbBvwAAAMAUVY+/AAAAgEt+oD8AAACgbUu8vwAAAECARpO/AAAAQDYqpL8A
    AABg1z/OPwAAAIDHebg/AAAAoEzWsr8AAABAJsjCvwAAAEABPrc/AAAAAAbyv78AAAAgYuaovwAA
    AIDW14E/AAAAoK1zx78AAABgF2PGvwAAAOCHj9S/AAAAAAZWjb8AAADgyG3WPwAAAEAwRLA/AAAA
    AEufxb8AAABABFKcPwAAAKDM3Xi/AAAAAEiZfj8AAAAAUxfDPwAAAEAH2sE/AAAAwMn9pb8AAAAA
    DV+AvwAAAAAnA8e/AAAAAPaGgD8AAAAgQfTGPwAAACD3iLi/AAAAgCgKob8AAABAVD7HPwAAAICW
    BKC/AAAAwMidqT8AAACAPwagPwAAAAByfHY/AAAAIPGIsL8AAABgxMKyPwAAAECqq8K/AAAAAHlt
    gz8AAABAsj67PwAAAOCYKZc/AAAAAMJ+kj8AAADgLS60PwAAACBWgrq/AAAAwBfzqD8AAACAdziV
    vwAAAACdEJc/AAAAoJkmsT8AAACAfjWtvwAAAKCJdMK/AAAAIB6PuL8AAADAfWm0PwAAACClLMa/
    AAAAAPMFyD8AAACAyk/HPwAAAAAT+7E/AAAAIFRVwj8AAAAAQSW4PwAAAIBrGbY/AAAAgDM+s78A
    AACAM/KkPwAAAIBxJ8u/AAAAgERAYb8AAAAAiimqPwAAAAA2TqA/AAAAAI9FrD8AAAAAwB04Pw==
- !!python/object/apply:numpy.core.multiarray._reconstruct
  args:
  - *id001
  - !!python/tuple
    - 0
  - !!binary |
    Yg==
  state: !!python/tuple
  - 1
  - !!python/tuple
    - 128
  - *id002
  - false
  - !!binary |
    AAAAoENBxL8AAACAnwenvwAAAIBQA5U/AAAA4Enptr8AAABAPe/HvwAAAAAAjGQ/AAAAIBezs78A
    AABgVvejvwAAACAo8sM/AAAAwDHow78AAACATN/FPwAAAMDYFJe/AAAAAENcy78AAAAA1/CfPwAA
    AGAz0aa/AAAA4FcXxD8AAAAAS9/DvwAAAGCoOL+/AAAAoIuXr78AAAAAChuyvwAAAOCM/5o/AAAA
    gMgQkj8AAAAAmPlbPwAAAMD26aw/AAAAIMb2uL8AAACATLfYvwAAAKDaYMG/AAAAAEvov78AAAAg
    bQqUvwAAAAAMYKa/AAAAgLNGqL8AAABAKPeXPwAAAIAkKcG/AAAAAKAfNz8AAACArouZPwAAAMCD
    VcA/AAAAAE/er78AAABANRO+vwAAACBFKsg/AAAAQIR2lj8AAADA7LLJvwAAAIDZPae/AAAAgIW0
    tT8AAADgZ+7HPwAAAECtqcE/AAAAIAefrj8AAACgHgSVPwAAAID4062/AAAAAMEmwD8AAABAG0XK
    vwAAAAD5OaY/AAAAQOvCxj8AAADgScGyPwAAAIC7vrI/AAAAAAPcrz8AAACA7ry2vwAAAACqg7Y/
    AAAAAF8Dwz8AAAAAjE2/vwAAAIDbi4k/AAAA4B97pz8AAABg/gu7vwAAACBSdKK/AAAA4KutsL8A
    AADgSrbRPwAAAMBMo8I/AAAAgEBjvb8AAAAgdbjCvwAAAEBpjLg/AAAAoEmzxL8AAAAg6bbAvwAA
    AABQYzQ/AAAAwEBZyb8AAACAt6vHvwAAAIAIzdG/AAAAAJDilT8AAAAAp17WPwAAAKAQMMI/AAAA
    wKlLv78AAAAAIiyxPwAAAIA2PKK/AAAAgFGMmb8AAAAgolK8PwAAAABER8U/AAAAwKvmpL8AAAAA
    wsyMvwAAAKCWzLa/AAAAAABnfT8AAAAAId/LPwAAAICTRLK/AAAAALmnfz8AAADgu63EPwAAAAAg
    R42/AAAAQBQItz8AAADAbEGBPwAAAAD22aA/AAAAYMxuu78AAAAgVRuhvwAAAGCQPbS/AAAAAEZ1
    kb8AAABgZlW2PwAAAKArTHg/AAAAAHpTlb8AAAAAS9yuPwAAAGABPsS/AAAAADZcrj8AAABAT+mu
    vwAAAEBbBKS/AAAAAPq3fL8AAACACT+vvwAAACC53by/AAAAAHjNqr8AAADgrg3BPwAAAOApD8i/
    AAAAwBdzxz8AAADguIrIPwAAAGCiupI/AAAAYC/1wz8AAABAU8vCPwAAAIB42aQ/AAAAwFMEoL8A
    AAAAvMKSvwAAACDEVsu/AAAAQFaPoL8AAAAAzsm3PwAAAABIH4Y/AAAAAIGyoz8AAAAAZCSAvw==
- !!python/object/apply:numpy.core.multiarray._reconstruct
  args:
  - *id001
  - !!python/tuple
    - 0
  - !!binary |
    Yg==
  state: !!python/tuple
  - 1
  - !!python/tuple
    - 128
  - *id002
  - false
  - !!binary |
    AAAAwAy9wb8AAAAgEru+PwAAACCDdrk/AAAAADrTsb8AAABgcbDBvwAAAOBB0Li/AAAAoKOut78A
    AACgj1a4vwAAAOBT88A/AAAAAEFfub8AAACAlhPQPwAAACCOe7e/AAAAQDQuyL8AAABA3/yyvwAA
    AADGW5e/AAAAgANw0D8AAAAACwfQvwAAAABkLb+/AAAAoGlekL8AAACAk26dvwAAAID+aqI/AAAA
    AHQ3ir8AAADgSh+cPwAAAADZG7Q/AAAAoP7Ytr8AAABgJ8LavwAAAECekau/AAAAgDk0uL8AAACA
    JomGvwAAAABoqpK/AAAAQEVurr8AAABAqqWvPwAAAMA6pcC/AAAAgPIMqL8AAABA5X20PwAAAOA8
    97g/AAAAwA03pb8AAABAheyivwAAAIBYmcY/AAAAwMtyqr8AAAAAH6bSvwAAAIB1d60/AAAAQHka
    xj8AAACAIqXMPwAAAEBWls8/AAAAAGtsqT8AAABAtZ+oPwAAAGBJ3MG/AAAAQK+Qxj8AAAAA7crI
    vwAAACBx0o2/AAAAQHa0xT8AAAAgyJu2PwAAAIBjsKY/AAAAwLE6sD8AAADgFRW8vwAAAAD2Dp2/
    AAAAgNgRxz8AAABACrXLvwAAAMCLG5Y/AAAAwP8fvT8AAACgttK4vwAAAKDfUZm/AAAAwCmkv78A
    AAAAZhXRPwAAAEBEP8E/AAAAYFQezL8AAACACuDBvwAAACCLFMI/AAAAoGoHxb8AAADAH1K3vwAA
    AIBuS58/AAAAADxdwb8AAAAAE6LJvwAAAKB9ntW/AAAAADqikL8AAABAqdDTPwAAAODvZ7c/AAAA
    wGQ5w78AAACAsKqkPwAAAAAQt4e/AAAAAMW5ir8AAAAAFF6hPwAAAIDxvM4/AAAAQM9dk78AAAAA
    Q3OUvwAAACBIkqO/AAAAAJGBqr8AAABgkg3GPwAAAIAHnqS/AAAAAOvtsD8AAABA/G3MPwAAAMDY
    XpG/AAAAQEanrz8AAACAKKylvwAAAGA9Y7k/AAAAwMGFxr8AAADAXnaYvwAAAOCQGsa/AAAAgOhP
    l78AAAAA3SG4vwAAAIA4iqa/AAAAANB7fz8AAABA2I+xPwAAAICvYMa/AAAAIFXwuT8AAADAqJOm
    vwAAAMBCLKI/AAAAQK4jqb8AAAAA3J6JPwAAAAB9oZc/AAAAgLXIrr8AAAAgAh2yPwAAAAD+B82/
    AAAAoH/pyz8AAAAgeUzIPwAAAKDQ0K4/AAAAIF2+wj8AAABAr2+7PwAAAMB0Qac/AAAAAFQIc78A
    AAAA54apvwAAAABZQsK/AAAAICNgo78AAABgWKmjPwAAAOBoE7S/AAAAgCHmsj8AAAAAkvJ3Pw==
